In [ ]:
import pandas as pd

In [16]:
converter_df = pd.read_csv('./final_data/zip_to_uhf34.csv')
trees_raw_df = pd.read_csv('./final_data/tree_data/census_2015/street_tree_census_2015.csv')
ozone_df = pd.read_csv('./final_data/environment_data/ozone.csv')
pm_df = pd.read_csv('./final_data/environment_data/PM.csv')
temp_df = pd.read_csv('./final_data/environment_data/temperature.csv')

In [176]:
ozone_df = pd.read_csv('./final_data/environment_data/ozone.csv')
pm_df = pd.read_csv('./final_data/environment_data/PM.csv')
temp_df = pd.read_csv('./final_data/environment_data/temperature.csv')

In [177]:
ozone_borough_df = ozone_df.query('GeoRank==1 & TimePeriod > "2√"').drop(columns=['TimePeriod','GeoType','GeoRank','10th percentile ppb','90th percentile ppb'])
ozone_borough_df = ozone_borough_df.groupby('Geography').mean()

ozone_UHF_df = ozone_df.query('GeoRank==3 & TimePeriod > "2√"').drop(columns=['TimePeriod','GeoType','GeoRank','10th percentile ppb','90th percentile ppb'])
ozone_UHF_group = ozone_UHF_df.groupby('GeoID')
ozone_UHF_df = ozone_UHF_group[['Mean ppb']].mean()
ozone_UHF_df['Geography'] = ozone_UHF_group[['Geography']].first()

pm_borough_df = pm_df.query('GeoRank==1 & TimePeriod < "B"').drop(columns=['TimePeriod','GeoType','GeoRank','10th percentile mcg/m3','90th percentile mcg/m3'])
pm_borough_df = pm_borough_df.groupby('Geography').mean()

pm_UHF_df = pm_df.query('GeoRank==3 & TimePeriod < "B"').drop(columns=['TimePeriod','GeoType','GeoRank','10th percentile mcg/m3','90th percentile mcg/m3'])
pm_UHF_group = pm_UHF_df.groupby('GeoID')
pm_UHF_df = pm_UHF_group[['Mean mcg/m3']].mean()
pm_UHF_df['Geography'] = pm_UHF_group[['Geography']].first()
pm_UHF_df.reset_index()


temp_borough_df = temp_df.query('GeoRank==1').drop(columns=['TimePeriod','GeoType','GeoRank'])
temp_borough_df = temp_borough_df.groupby('Geography').mean()

temp_UHF42_df = temp_df.query('GeoRank==4').drop(columns=['TimePeriod','GeoType','GeoRank'])
temp_UHF42_df['GeoID'].replace(305,305307, inplace=True)
temp_UHF42_df['GeoID'].replace(307,305307, inplace=True)
temp_UHF42_df['GeoID'].replace(306,306308, inplace=True)
temp_UHF42_df['GeoID'].replace(308,306308, inplace=True)
temp_UHF42_df['GeoID'].replace(309,309310, inplace=True)
temp_UHF42_df['GeoID'].replace(404,404406, inplace=True)
temp_UHF42_df['GeoID'].replace(406,404406, inplace=True)
temp_UHF42_df['GeoID'].replace(501,501502, inplace=True)
temp_UHF42_df['GeoID'].replace(502,501502, inplace=True)
temp_UHF42_df['GeoID'].replace(503,503504, inplace=True)
temp_UHF42_df['GeoID'].replace(504,503504, inplace=True)
temp_UHF42_df['GeoID'].replace(105,105106107, inplace=True)
temp_UHF42_df['GeoID'].replace(106,105106107, inplace=True)
temp_UHF42_df['GeoID'].replace(107,105106107, inplace=True)
temp_UHF42_group = temp_UHF42_df.groupby('GeoID')
temp_UHF_df = temp_UHF42_group[['Degrees Fahrenheit']].mean()
temp_UHF_df['Geography'] = temp_UHF42_group[['Geography']].first()
temp_UHF_df.reset_index()
temp_UHF_group = temp_UHF_df.groupby('GeoID')
temp_UHF_df = temp_UHF_group['Degrees Fahrenheit'].mean()
temp_UHF_df['Geography'] = temp_UHF_group['Geography'].first()

In [178]:
combined_env_UHF_df = pd.merge(temp_UHF_df, pm_UHF_df, left_on="GeoID", right_on="GeoID",how="inner", sort=False)
combined_env_UHF_df = pd.merge(combined_env_UHF_df, ozone_UHF_df, left_on="GeoID", right_on="GeoID",how="inner", sort=False )
combined_env_UHF_df['UHF34 Neighborhood Name'] = combined_env_UHF_df['Geography_x']
combined_env_UHF_df = combined_env_UHF_df.drop(columns=['Geography_x', 'Geography_y'])

combined_env_borough_df = pd.merge(temp_borough_df, pm_borough_df, left_on="Geography", right_on="Geography",how="inner", sort=False)
combined_env_borough_df = pd.merge(combined_env_borough_df, ozone_borough_df, left_on="Geography", right_on="Geography",how="inner", sort=False )
combined_env_borough_df=combined_env_borough_df.reset_index()
combined_env_borough_df['Borough'] = combined_env_borough_df['Geography']
combined_env_borough_df = combined_env_borough_df.drop(columns=['Geography', 'GeoID_x', 'GeoID_y', 'GeoID'])
combined_env_borough_df

   Degrees Fahrenheit  Mean mcg/m3   Mean ppb        Borough
0                97.1     8.385714  31.007143          Bronx
1                98.6     8.114286  31.664286       Brooklyn
2                98.3     9.628571  27.250000      Manhattan
3               100.0     7.778571  32.135714         Queens
4                97.4     7.371429  31.521429  Staten Island

In [179]:
trees_raw_df['zipcode'].replace(83,10023, inplace=True)
trees_raw_df['zipcode'].replace(10111,10001, inplace=True)
trees_raw_df['zipcode'].replace(10115,10027, inplace=True)
trees_raw_df['zipcode'].replace(10281,10282, inplace=True)
trees_raw_df['zipcode'].replace(11096,11691, inplace=True)
trees_raw_df['zipcode'].replace(11249,11222, inplace=True)
trees_raw_df['zipcode'].replace(11251,11205, inplace=True)
trees_raw_df['zipcode'].replace(11360,11357, inplace=True)
trees_raw_df['zipcode'].replace(11371,11369, inplace=True)
trees_raw_df['zipcode'].replace(11451,11433, inplace=True)
trees_df = pd.merge(trees_raw_df, converter_df, left_on="zipcode", right_on="zipcode",how="left", sort=False)
trees_df = trees_df.drop(columns=['created_at','tree_id','block_id','the_geom','boroname','stump_diam','curb_loc','spc_latin','spc_common','steward','guards','sidewalk','user_type','problems','root_stone','root_grate','root_other','trnk_wire','trnk_light','trnk_other','brnch_ligh','brnch_shoe','brnch_othe','address','zip_city','cb_num','cncldist','st_assem','st_senate','nta','nta_name','boro_ct','state','x_sp','y_sp'])
trees_df.fillna("Dead",inplace=True)
trees_df['health'].replace("Good", 3, inplace=True)
trees_df['health'].replace("Fair", 2, inplace=True)
trees_df['health'].replace("Poor", 1, inplace=True)
trees_df['health'].replace("Dead", 0, inplace=True)
trees_df.drop(columns=['zipcode','borocode', 'status'],inplace=True)

In [180]:
trees_borough_df = trees_df.drop(columns=['Latitude','longitude', 'UHF34 Code','UHF34 Neighborhood Name'])
trees_grouped_borough = trees_borough_df.groupby('Borough')
trees_borough_df = trees_grouped_borough.mean()
trees_borough_df['Number of Trees'] = trees_grouped_borough['health'].count()
trees_UHF_df = trees_df.drop(columns=['Latitude','longitude'])
trees_grouped_UHF = trees_UHF_df.groupby('UHF34 Neighborhood Name')
trees_UHF_df = trees_grouped_UHF[['health','tree_dbh']].mean()
trees_UHF_df['Borough'] = trees_grouped_UHF[['Borough']].first()
trees_UHF_df['UHF34 Code'] = trees_grouped_UHF[['UHF34 Code']].first()
trees_UHF_df['Number of Trees'] = trees_grouped_UHF[['health']].count()

In [186]:
combined_UHF_df = pd.merge(trees_UHF_df, combined_env_UHF_df, left_on="UHF34 Code", right_on="GeoID",how="inner", sort=False)
combined_borough_df = pd.merge(trees_borough_df, combined_env_borough_df, left_on="Borough", right_on="Borough",how="inner", sort=False)
combined_UHF_df.rename(columns={"health": "Average Status","tree_dbh": "Average Diameter",  "Degrees Fahrenheit": "Average Summer Surface Temperature", "Mean mcg/m3": "Average Fine Particle Pollution", "Mean ppb": "Average Ozone Pollution"}, inplace=True)
combined_borough_df.rename(columns={"tree_dbh": "Average Diameter", "health": "Average Status", "Degrees Fahrenheit": "Average Summer Surface Temperature", "Mean mcg/m3": "Average Fine Particle Pollution", "Mean ppb": "Average Ozone Pollution"}, inplace=True)
trees_df.rename(columns={"tree_dbh": "Diameter", "health": "Status", "Latitude":"Lat", "longitude": "Long"}, inplace=True)

In [187]:
trees_df

,Diameter,Status,Lat,Long,UHF34 Code,UHF34 Neighborhood Name,Borough
0,3,2,40.723092,-73.844215,405,Ridgewood/Forest Hills,Queens
1,21,2,40.794111,-73.818679,403,Flushing/Clearview,Queens
2,3,3,40.717581,-73.936608,201,Greenpoint,Brooklyn
3,10,3,40.713537,-73.934456,201,Greenpoint,Brooklyn
4,21,3,40.666778,-73.975979,202,Downtown Brooklyn/Heights/Slope,Brooklyn
...,...,...,...,...,...,...,...
683783,25,3,40.713211,-73.954944,201,Greenpoint,Brooklyn
683784,7,3,40.715194,-73.856650,405,Ridgewood/Forest Hills,Queens
683785,12,3,40.620762,-74.136517,503504,Southern Staten Island,Staten Island
683786,9,3,40.850828,-73.903115,105106107,The South Bronx,Bronx
683787,23,2,40.732165,-73.787526,404406,Bayside/Little Neck/Fresh Meadows,Queens

In [188]:
combined_borough_df

,Borough,Average Diameter,Average Status,Number of Trees,Average Summer Surface Temperature,Average Fine Particle Pollution,Average Ozone Pollution
0,Bronx,9.693649,2.636973,85203,97.1,8.385714,31.007143
1,Brooklyn,11.739312,2.657981,177300,98.6,8.114286,31.664286
2,Manhattan,8.473641,2.577121,65423,98.3,9.628571,27.250000
3,Queens,12.557591,2.636343,250544,100.0,7.778571,32.135714
4,Staten Island,10.492746,2.671101,105318,97.4,7.371429,31.521429

In [189]:
combined_UHF_df

,Average Status,Average Diameter,Borough,UHF34 Code,Number of Trees,Average Summer Surface Temperature,Average Fine Particle Pollution,Average Ozone Pollution,UHF34 Neighborhood Name
0,2.709569,13.385147,Brooklyn,209,14327,94.8,7.671429,31.921429,Bensonhurst - Bay Ridge
1,2.690632,14.122453,Queens,404406,36177,97.6,7.600000,31.471429,Bayside Little Neck-Fresh Meadows
2,2.705653,11.143644,Brooklyn,203,19973,98.5,8.214286,30.542857,Bedford Stuyvesant - Crown Heights
3,2.676278,13.192261,Brooklyn,206,21398,98.6,7.907143,31.264286,Borough Park
4,2.653037,14.679529,Brooklyn,208,19100,95.9,7.578571,33.800000,Canarsie - Flatlands
5,2.612845,8.458788,Manhattan,302,7692,97.4,8.700000,28.621429,Central Harlem - Morningside Heights
6,2.568078,7.854588,Manhattan,306308,11127,98.15,10.750000,25.735714,Chelsea-Village
7,2.548733,13.157876,Brooklyn,210,19186,97.1,7.428571,33.900000,Coney Island - Sheepshead Bay
8,2.643752,10.722880,Brooklyn,202,20511,97.6,8.928571,29.078571,Downtown - Heights - Slope
9,2.476652,7.737649,Manhattan,303,4433,97.6,8.728571,29.150000,East Harlem
10,2.645832,8.661414,Brooklyn,204,16879,99.9,8.071429,32.028571,East New York
11,2.702469,12.829372,Brooklyn,207,17336,98.0,8.000000,31.442857,East Flatbush - Flatbush
12,2.687985,12.940608,Queens,403,33085,99.4,7.885714,31.942857,Flushing - Clearview
13,2.609023,9.738140,Bronx,103,10750,95.5,8.342857,30.528571,Fordham - Bronx Pk
14,2.698008,9.274022,Brooklyn,201,9689,99.6,9.450000,30.171429,Greenpoint
15,2.687522,12.649639,Queens,408,34316,101.4,7.657143,31.850000,Jamaica
16,2.650018,11.492357,Bronx,101,5626,92.2,8.228571,29.692857,Kingsbridge - Riverdale
17,2.638746,10.106337,Queens,401,15150,99.1,8.942857,30.842857,Long Island City - Astoria
18,2.693638,10.941637,Staten Island,501502,27980,97.05,7.485714,30.550000,Northern SI
19,2.737727,10.578699,Bronx,104,23914,96.0,8.150000,31.957143,Pelham - Throgs Neck
20,2.589112,12.268779,Queens,405,25973,96.6,7.950000,31.421429,Ridgewood - Forest Hills
21,2.634119,13.142482,Queens,409,38805,100.6,7.278571,32.542857,Southeast Queens
22,2.662947,10.330342,Staten Island,503504,77338,94.85,7.342857,31.914286,Southern SI
23,2.633629,13.902023,Queens,407,26394,100.3,7.557143,32.321429,Southwest Queens
24,2.659791,10.016355,Brooklyn,205,6787,96.3,8.635714,30.371429,Sunset Park
25,2.667198,11.900405,Bronx,102,15051,99.2,8.142857,31.392857,Northeast Bronx
26,2.325394,7.385341,Queens,410,12511,92.7,6.807143,36.578571,Rockaways
27,2.548657,7.517748,Bronx,105106107,29862,99.266667,8.842857,30.485714,South Bronx
28,2.612334,8.105829,Manhattan,309310,7994,97.8,9.650000,26.907143,Union Square-Lower Manhattan
29,2.534810,8.628737,Manhattan,305307,13947,96.95,10.500000,25.842857,Upper East Side-Gramercy
30,2.710493,10.212770,Manhattan,304,10321,95.5,9.092857,27.578571,Upper West Side
31,2.496720,7.776567,Manhattan,301,9909,94.0,8.657143,28.928571,Washington Heights
32,2.629581,11.801301,Queens,402,28133,99.9,8.542857,31.085714,West Queens
33,2.611194,8.712647,Brooklyn,211,12114,100.6,8.850000,30.378571,Williamsburg - Bushwick